### ISSUE TITLE
Family

### ISSUE THREAD

**Issue by torstees** [NIH-NCPI/ncpi-fhir-ig-2#17]
This issue holds the Codeathon's FSH follow-up work and MVP deliverables targeted for 08/13. The PRs intended to be merged should contain, at a minimum, the following: 

- [x] Module Content: 
  - Should contain the logical model, profiles, extensions, and codesystems. 
    - File: input/fsh/modules/[module].fsh 
      - Example: [Participants](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/21/files#diff-f589bc4452ae064aecb5ce946d608d90615a8c31e868dfbc547978b2b5909d38)

- [x] Examples Page:
  - This file should contain at least one example of mapped data. 
    - File: input/fsh/examples/[module].fsh   
      - Example: [Participants](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/21/files#diff-ede06508cefe3c8820f1111fb23fb8a24b4c16e91f7b044b0fc63dcca00cbf93)

- [x] Info Pages: 
  - Intro for Logical Model
    - File: input/pagecontent/StructureDefinition-SharedDataModel[Module]-intro.md
      - Example: [Participants](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/21/files#diff-c750dedd592d39f04b68d6db7e5531ae30ead2a78aa1815940682cedb5d16fd3)
  - Intro for Profile: 
    - Must contain: 
      - 'Added Profile Restrictions' - Describing the restrictions to generate interoperable resources. 
      - 'Recommended Practices' - TBD
      - 'FHIR Mappings Table'
        - Example: [Participants](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/21/files#diff-82132b0bfdb15c10db1dc37ffa606615468ea4f90b46ff1940a04d1513713ade)
  - Profile Notes Page **(Optional)**
    - Any additional, helpful information.
      - Example: [Participant](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/21/files#diff-6f3897d85717adaf7607dca8c34fba6b0ccc17a736543ecc5ea9ebaff2b48669)

**Comment by brendagutman** [comment]
Initial working branch `bg_family`. Might reorganize later.
