### ISSUE TITLE
IG V2 Business Writing: ResearchStudy 

### ISSUE THREAD

**Issue by JamedFV** [NIH-NCPI/ncpi-fhir-ig-2#34]
This issue holds all business writing requirements for the IG V2 update. The content intended to be merged in this issue includes the following: 

- [ ] Module Overview 
     - Content to enable users to understand how FHIR entities relate to real world data
          - https://nih-ncpi.github.io/ncpi-fhir-ig-2/module_research_study.html

- [ ] Use Case Guide
     - Content to inform users how to build and improve queries 
          - https://nih-ncpi.github.io/ncpi-fhir-ig-2/use_case_tbd.html         

- [ ]  TBD

**Comment by calkinsh** [comment]
hi Jamed, we have some text already from the MVP of research study - can any of that be reused? It is here:

https://docs.google.com/document/d/1Vn9KWA-Z-59qBLlSPuDR5V9JgRrcKDrbfKveJ3cLu2k/edit#heading=h.b785p6b8s1aw
